### ISSUE TITLE
adding images, they dont show as thumbnails

### ISSUE THREAD

**Issue by nlaurance** [PythonIreland/website#121]
I tried adding a new sponsor logo, and the image pipeline seems KO

**Comment by davgibbs** [comment]
Hi @nlaurance I can try recreate this issue on my local development. Is there a screenshot of where the image is uploaded or where it should appear. Or any more details available?

**Comment by matrixise** [comment]
@nlaurance The problem was with the new version of `django-storages` and the default configuration of the S3 Bucket (private). By default, in the new version of `django-storages`, this one will use the ACL of the parent. If this one is private, the children will also be private. 

See this commit: https://github.com/PythonIreland/website/commit/72f020ca3de4c09b32b1f68e0ec1b182b15249e6
